/**
 * @file colors.h
 * @author Mattia Forlin, Matteo Toffoli
 * @brief colors's header file.
 * @date 2022-08-29
 *
 * @copyright Copyright (c) 2022
 *
 */

#define ANSI_COLOR_BLACK "\x1b[30m"
#define ANSI_COLOR_RED "\x1b[31m"
#define ANSI_COLOR_GREEN "\x1b[32m"
#define ANSI_COLOR_YELLOW "\x1b[33m"
#define ANSI_COLOR_BLUE "\x1b[34m"
#define ANSI_COLOR_PURPLE "\x1b[35m"
#define ANSI_COLOR_CYAN "\x1b[36m"
#define ANSI_COLOR_WHITE "\x1b[37m"

#define BOLD_ANSI_COLOR_BLACK "\x1b[1;30m"
#define BOLD_ANSI_COLOR_RED "\x1b[1;31m"
#define BOLD_ANSI_COLOR_GREEN "\x1b[1;32m"
#define BOLD_ANSI_COLOR_YELLOW "\x1b[1;33m"
#define BOLD_ANSI_COLOR_BLUE "\x1b[1;34m"
#define BOLD_ANSI_COLOR_PURPLE "\x1b[1;35m"
#define BOLD_ANSI_COLOR_CYAN "\x1b[1;36m"
#define BOLD_ANSI_COLOR_WHITE "\x1b[1;37m"

#define UNDERLINE_ANSI_COLOR_BLACK "\x1b[4;30m"
#define UNDERLINE_ANSI_COLOR_RED "\x1b[4;31m"
#define UNDERLINE_ANSI_COLOR_GREEN "\x1b[4;32m"
#define UNDERLINE_ANSI_COLOR_YELLOW "\x1b[4;33m"
#define UNDERLINE_ANSI_COLOR_BLUE "\x1b[4;34m"
#define UNDERLINE_ANSI_COLOR_PURPLE "\x1b[4;35m"
#define UNDERLINE_ANSI_COLOR_CYAN "\x1b[4;36m"
#define UNDERLINE_ANSI_COLOR_WHITE "\x1b[4;37m"

#define ANSI_COLOR_BLACK_BACKGROUND "\x1b[40m"
#define ANSI_COLOR_RED_BACKGROUND "\x1b[41m"
#define ANSI_COLOR_GREEN_BACKGROUND "\x1b[42m"
#define ANSI_COLOR_YELLOW_BACKGROUND "\x1b[43m"
#define ANSI_COLOR_BLUE_BACKGROUND "\x1b[44m"
#define ANSI_COLOR_PURPLE_BACKGROUND "\x1b[45m"
#define ANSI_COLOR_CYAN_BACKGROUND "\x1b[46m"
#define ANSI_COLOR_WHITE_BACKGROUND "\x1b[47m"

#define ANSI_COLOR_BLACK_HIGH_BACKGROUND "\x1b[0;100m"
#define ANSI_COLOR_RED_HIGH_BACKGROUND "\x1b[0;101m"
#define ANSI_COLOR_GREEN_HIGH_BACKGROUND "\x1b[0;102m"
#define ANSI_COLOR_YELLOW_HIGH_BACKGROUND "\x1b[0;103m"
#define ANSI_COLOR_BLUE_HIGH_BACKGROUND "\x1b[0;104m"
#define ANSI_COLOR_PURPLE_HIGH_BACKGROUND "\x1b[0;105m"
#define ANSI_COLOR_CYAN_HIGH_BACKGROUND "\x1b[0;106m"
#define ANSI_COLOR_WHITE_HIGH_BACKGROUND "\x1b[0;107m"

#define HIGH_ANSI_COLOR_BLACK "\x1b[0;90m"
#define HIGH_ANSI_COLOR_RED "\x1b[0;91m"
#define HIGH_ANSI_COLOR_GREEN "\x1b[0;92m"
#define HIGH_ANSI_COLOR_YELLOW "\x1b[0;93m"
#define HIGH_ANSI_COLOR_BLUE "\x1b[0;94m"
#define HIGH_ANSI_COLOR_PURPLE "\x1b[0;95m"
#define HIGH_ANSI_COLOR_CYAN "\x1b[0;96m"
#define HIGH_ANSI_COLOR_WHITE "\x1b[0;97m"

#define BOLD_HIGH_ANSI_COLOR_BLACK "\x1b[1;90m"
#define BOLD_HIGH_ANSI_COLOR_RED "\x1b[1;91m"
#define BOLD_HIGH_ANSI_COLOR_GREEN "\x1b[1;92m"
#define BOLD_HIGH_ANSI_COLOR_YELLOW "\x1b[1;93m"
#define BOLD_HIGH_ANSI_COLOR_BLUE "\x1b[1;94m"
#define BOLD_HIGH_ANSI_COLOR_PURPLE "\x1b[1;95m"
#define BOLD_HIGH_ANSI_COLOR_CYAN "\x1b[1;96m"
#define BOLD_HIGH_ANSI_COLOR_WHITE "\x1b[1;97m"

#define ANSI_COLOR_RESET "\x1b[0m"